"""
schema.py
Defines the strict structural constraints for specifications and AI execution plans.
Supports universal dynamic path mapping across external applications.
"""
from pydantic import BaseModel, Field
from typing import List, Optional

class FeatureSpec(BaseModel):
    """The formal structural contract for a feature specification."""
    feature_objective: str = Field(
        ..., description="The high-level goal of what this feature aims to solve."
    )
    user_story: str = Field(
        ..., description="The standard Agile narrative format (As a... I want... So that...)."
    )
    business_rules: List[str] = Field(
        ..., min_length=1, description="List of strict boundaries, behaviors, or business constraints."
    )
    acceptance_criteria: List[str] = Field(
        ..., min_length=1, description="Scenarios that must pass to consider this feature functionally complete."
    )
    non_functional_requirements: Optional[List[str]] = Field(
        default=[], description="Performance, security, or style standards (e.g., PEP8)."
    )
    out_of_scope_items: Optional[List[str]] = Field(
        default=[], description="Explicit constraints outlining what this pipeline should NOT implement."
    )

class ImplementationPlan(BaseModel):
    """The structured blueprint generated by the AI architect outlining how the feature will be engineered."""
    technical_summary: str = Field(
        ..., description="A brief overview explaining the technical strategy to solve the spec requirements."
    )
    impacted_files: List[str] = Field(
        ..., description="The exact filenames selected from the provided project directory snapshot that must be modified or created (e.g., ['app.py'])."
    )
    codebase_contract: dict = Field(
        ..., description="The structural interface mapping out expected module properties (e.g., {'global_variables': ['input_path'], 'classes': ['PandasCSVProcessor'], 'functions': ['main']}) so tests match the code."
    )
    tasks: List[str] = Field(
        ..., description="A step-by-step ordered list of engineering tasks required to build the feature."
    )
    risks: List[str] = Field(
        ..., description="Potential edge cases, security considerations, or regression bugs to watch out for."
    )