"""
core/models.py
Domain data structures and schemas used across the pipeline orchestration framework.
Defines strict validation contracts using Pydantic.
"""
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Union

class FeatureSpec(BaseModel):
    """Data validation layer mapping feature configuration spec documents."""
    feature_objective: str = Field(..., description="High-level target functional goal of the feature.")
    user_story: str = Field(..., description="The user persona narrative context.")
    business_rules: List[str] = Field(default_factory=list, description="Hard operational restrictions.")
    acceptance_criteria: List[str] = Field(default_factory=list, description="Verification checks for completion.")

class ImplementationPlan(BaseModel):
    """Structural blueprint schema generated by the AI architectural planning layer."""
    technical_summary: str = Field(..., description="High-level architectural execution strategy summary.")
    impacted_files: List[str] = Field(..., description="Collection of Python script targets slated for code modifications.")
    tasks: List[str] = Field(..., description="Granular, ordered checklist items for the development context framework.")
    codebase_contract: Union[Dict[str, Any], Any] = Field(
        ..., 
        description="The strict interface contract (global variables, classes, functions) required for synthesis and testing validation."
    )